package com.example.panoramic.remote.model

data class UserInfoDto(
    val account_number: String,
    val age: String,
    val bank_name: String,
    val card_number: String,
    val child_number: String,
    val city: String,
    val created_at: String,
    val edu_level: String,
    val email: String,
    val id: Int,
    val last_name: String,
    val marital_status: Int,
    val mobile_number: String,
    val name: String,
    val national_id: String,
    val national_photo: String,
    val prof_pic: String,
    val rank: String,
    val score_num: String,
    val score_total: String,
    val shaba: String,
    val shop_address: String,
    val shop_id: String,
    val shop_name: String,
    val shop_zip: String,
    val shopkeeper: String,
    val success: Boolean,
    val unseen_film: String,
    val unseen_notification: String
)